config/routes.rb
Tracker::Application.routes.draw do
  resources :users
  resources :projects do
    member do
      get  'users'
      get  'add_user'
      put  'adds_user'
      match  'removes_user/:user_id', :action => 'removes_user_from', :via => :put, :as => :removes_user_from
    end
    resources :features
  end
  root :to => 'projects#index'
end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :project

  STATES = [:backlog, :started, :in_progress]

  def state
    STATES[state_id]
  end

  def state= new_state
    self.state_id = STATES.index(new_state)
  end

  def scenarios
    total = []
    n = 0

    body.split("\n").each do |line|
      if r = line =~ /Scenario: (.*)/

        if total[n].nil?
          total[n] =  {title: line[(r+10)..-1], body: []}
        else
          n += 1
        end
      else

        total[n][:body] << line.strip unless line.strip == ""
      end
    end
    total
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :features


  def remove_user(user)
    self.users.delete(user)
  end

  def assign_user(user)
    self.users << user
  end
end

app/models/project_user.rb
class ProjectUser < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :projects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @feature = @project.features.new
  end

  def create
    @project = Project.find(params[:project_id])
    @feature = @project.features.create!(params[:feature])
    redirect_to project_path(@project)
  end

  def edit
    @project = Project.find(params[:project_id])
    @feature = @project.features.find(params[:id])
  end

  def update
    @feature = Feature.find(params[:id])
    @feature.update_attributes(params[:feature])
    redirect_to project_path(@project)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    Project.create!(params[:project])
    redirect_to projects_path
  end

  def add_user
    @project = Project.find(params[:id])
    @users = User.all
  end

  def adds_user
    @project = Project.find(params[:id])
    @project.users << User.find(params[:project][:users])
    redirect_to projects_path
  end

  def users
    @project = Project.find(params[:id])
  end

  def removes_user_from
    project = Project.find(params[:id])
    project.remove_user(User.find(params[:user_id]))
    redirect_to users_project_path(project)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    user = User.create!(params[:user])
    redirect_to users_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_menu.html.haml
%ul
  %li=link_to "projects", projects_path

app/views/features/_form.html.haml
=form_for [@project,@feature] do |f|
  %p
    =f.label :name
    =f.text_field :name
  %p
    =f.label :body
    =f.text_area  :body
  %p
    -Feature::STATES.each_with_index do |state, i|
      %span{class: "state_#{state}"}
        =radio_button 'feature', 'state_id', i
        =label_tag "feature_#{state}", state.to_s.gsub("_", " ")
  %p=f.submit 'Save'

app/views/features/edit.html.haml
%h1 Edit feature
=render(partial: "form")

app/views/features/new.html.haml
%h1== New feature for #{@project.name}
=render(partial: "form")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tracktor
  %body
    #menu=render(:partial => "common/menu")
    #content=yield

app/views/projects/add_user.html.haml
%h1==Add user to #{@project.name}
=form_for @project, :url => adds_user_project_path(@project) do |f|
  %p
    =label_tag "add_user"
    =collection_select("project", "users", @users, :id, :name)
  %p=f.submit "Add User"

app/views/projects/index.html.haml
%h1 Projects

%ul
  -@projects.each do |project|
    %li=link_to project.name, project_path(project)

app/views/projects/new.html.haml
%h1 Create Project

=form_for(@project) do |p|
  %p
    =p.label :name
    =p.text_field :name
  %p=p.submit

app/views/projects/show.html.haml
%h1== Project: #{@project.name}

=link_to "Add User", add_user_project_path(@project)
=link_to "Users", users_project_path(@project)
=link_to "New Feature", new_project_feature_path(@project)

%ul
  - @project.features.each do |feature|
    %li=link_to feature.name, edit_project_feature_path(@project,feature)

app/views/projects/users.html.haml
%h1 Users currently assigned to the project

%table
  %tr
    %th Name
    %th Remove
  -@project.users.each do |user|
    %tr{class: "user_#{user.id}"}
      %td=user.name
      %td=link_to "X", removes_user_from_project_path(@project,user.id), method: :put

app/views/users/index.html.haml
%h1 Users

%ul
  -@users.each do |user|
    %li=user

app/views/users/new.html.haml
%h1 New user

=form_for(@user) do |f|
  %p
    =f.label :name
    =f.text_field :name
  %p=f.submit